### PR TITLE
New feature: auto-register Plone users on login

### PR DESCRIPTION
**Pull request by alecghica**
- New feature implemented, so Plone users might be registered
  in automatic into the jabber server on login. Upgrade
  step was also added to update the new added property to
  existing installations.
  [alecghica]

### CODE REVIEW

**Comment by alecghica** [comment]
@jcbrand maybe you can give me a hint here, I still didn't find out why the auto-registered users are not (auto) subscribe to each other or to the other registered jabber users (ofc with "Auto-subscribe XMPP users" property set on True). Once a user got auto-registered it works to manually add an existing contact.

**Comment by jcbrand** [comment]
@alecghica The auto-subscribe feature results in the new user getting a  _roster item add suggestion_ for every other member in the site (see utils/setup.py:61).

First try it out by registering a non-logged-in user for XMPP in the control panel. Then go to the ejabberd admin (http://localhost:5280/admin), go to that specific user and you should see an offline message for that user. The offline message will be the roster suggestion.

Only once that user logs in and successfully communicates with the XMPP server will these suggestions be received and will that user then start sending subscription requests to these users. These requests will be "pending" until these users go online, at which point they will received the subscription requests and automatically approve and subscribe back.

Further debugging: 
- If you don't think the suggestion is created, check subscribeToAllUsers in utils/setup.py
- If the suggestion is created but something is perhaps wrong in JS, check subscribeToSuggestedItems in converse.js

**Comment by jcbrand** [comment]
Hi @alecghica 

Why exactly do you need/want this feature? What makes it better than registering all users for XMPP once via the control panel?

**Comment by alecghica** [comment]
Hi @jcbrand 

Thx for your explanations above, I'll look into right now. 

Regarding this new feature, for example make sense to auto-register users if you have quite some users and you want to be registered only those who are actually active, plus if new users are added intro the Plone system the administrator may forget to register them into the jabber server. Also will make admins life more easy not to register to jabber server the a user every time one is added into the system.

There is also a usecase I have, where auth into Plone is made via LDAP. LDAP server stores like 10k users but only a few of them are actually active and do login. I don't know who is active or who will be active and I don't want to register 10k jabber users, I want only the active ones.

**Comment by jcbrand** [comment]
Hi @alecghica 

> plus if new users are added intro the Plone system the administrator may forget to register them into the jabber server

New users are automatically registered in the Jabber server. See **onUserCreation** in _subscribers/user_management.py_

So the admin only has to register the users once, when XMPP is initially configured for the site. 

> There is also a usecase I have, where auth into Plone is made via LDAP

Do LDAP users perhaps not trigger this event?

>  I don't want to register 10k jabber users, I want only the active ones

We have ~6000 ldap users. I registered them all on the XMPP server and it took less than 10 minutes. The important thing is that you don't enable "auto-subscribe".

**Comment by alecghica** [comment]
Hi @jcbrand,

I removed auto_register property as indeed was not necessary. I also removed the associated import step.

I also fixed **"Deregister ALL Users"** function, as credentials were left un-deleted under IXMPPPasswordStorage resulting in various errors when register/deregister users.

Regarding the **register on login**, I still say its a useful feature so I will continue to pledge for it:

We now have 2 ways of registering users via the subscriber **onUserCreation** and manually via control panel from **register selected users**. If usernames are misspelled or forgotten when the manager will manually register all users the _register on login_ will cover this case and no more headaches to investigate why certain user is not registered on jabber server.

Having **register on login** on increase performance as you will not be forced to register on the jabber server all the users you have in the portal, they will be auto registered once they login. Like in your case instead of registering 10k users probably many of them totally inactive you can let the system take only the space it needs to.

Also for example in my case I want the "auto-subscribe" on and I have lets say 15k users. I want all users who login on the portal to be subscribed to each other. I don't want to register all the 15k users on the jabber server and subscribe everyone to everyone as the contact list will become too huge. I prefer to let them be registered one by one once they login in Plone with "auto-subscribe" on so everyone has everyone in contacts list.

If you decide to merge please don't do it yet :) ... as I am digging in something related to **auto_subscribe** feature.

**Comment by jcbrand** [comment]
> I removed auto_register property as indeed was not necessary. I also removed the associated import step.

Ok, but looks like LDAP users aren't registered automatically when they are created, so this is something we'll have to fix. 

> I also fixed "Deregister ALL Users" function, as credentials were left un-deleted under IXMPPPasswordStorage resulting in various errors when register/deregister users.

Nice, thanks!

> Regarding the register on login, I still say its a useful feature so I will continue to pledge for it:
> 
> We now have 2 ways of registering users via the subscriber onUserCreation and manually via control panel from register selected users. If usernames are misspelled or forgotten when the manager will manually register all users the register on login will cover this case and no more headaches to investigate why certain user is not registered on jabber server.

Yes, I can see that it might be useful. 

I think we should however update the code so that the user somehow gets a message upon first login (because they will have to reload the page for chat to work and users get confused/irritated very quickly).

So the_xmpp-loader_ view should return some indication that registration is happening now, and the javascript in jarnxmpp.core.handlers.js should inform the user. 

You know what would be cool, a JS script that can dynamically create Plone status messages (like IStatusMessage or whatever).

> Also for example in my case I want the "auto-subscribe" on and I have lets say 15k users. I want all users who login on the portal to be subscribed to each other. I don't want to register all the 15k users on the jabber server and subscribe everyone to everyone as the contact list will become too huge. I prefer to let them be registered one by one once they login in Plone with "auto-subscribe" on so everyone has everyone in contacts list.

Yeah, this is perhaps the best argument for "auto-register". :)

> If you decide to merge please don't do it yet :) ... as I am digging in something related to auto_subscribe feature.

Ok, were are actually deploying xmpp.core and xmpp.chat today, and I made two releases yesterday, so the code is a bit out of sync.

**Comment by alecghica** [comment]
Regarding _LDAP users aren't registered automatically when they are created_ I think this is quite a distinct problem, I'll add a separate issue for it.

Indeed, the message to reload is needed. I'll take a look now.

Don't worry about the out of sync, I'll do a merge later on.

**Comment by alecghica** [comment]
I added the issue regarding the LDAP registration on create under #11.

**Comment by alecghica** [comment]
@jcbrand a question regarding **auto_subscribe** feature, if you activate _auto_subscribe_ I see that when you manually register users they are subscribed only between those added in that particular adding session. Like if I add user1 and user2 they will be subscribed to each other, then later on if I register user3 and user4 they will be subscribed only between them and not with all the other registered users (as expected) like user1 and 2. Also when a user is registered when a new Plone user there is an attempt to register it towards all the Plone users, no matter what they are registered into the jabber server or not (even so I noticed the suggestion is sent but the user registered this way has no contacts in his list, this is a bug right?).

For the 3rd way a user can be registered via the auto-register on login (the feature i implemented in this pull request) I made that the registered user is subscribed only to the users registered into the jabber server (not to try to subscribe it to all plone users no matter they are registered in jabber server or not). I think this the correct way of auto-subscribe that should be done for all 3 ways of registering users. I implemented this under https://github.com/alecghica/collective.xmpp.core/blob/bdb8cc5314c649c3e72437accd3d913f74f16a1c/collective/xmpp/core/browser/loader.py  see bellow line 51. About this I have a problem as I cant figure it out why even so _sendRosterItemAddSuggestion_ is receiving the right list of users and send the suggestion, the user didn't has the users in his contacts.

**Comment by alecghica** [comment]
@jcbrand in the previous commit I fixed the issue with refresh on auto-register, no need for any message to ask user to refresh browser, I managed to bind the user on the fly right after he is registered to the jabber server.

It remains the problem I mentioned earlier with _auto_subscribe_. Waiting for some feedback from you on this.

**Comment by jcbrand** [comment]
> I see that when you manually register users they are subscribed only between those added in that particular adding session. Like if I add user1 and user2 they will be subscribed to each other, then later on if I register user3 and user4 they will be subscribed only between them and not with all the other registered users (as expected) like user1 and 2. 

This is a bug, and I can see why. **registerXMPPUsers** in _collective.xmpp.core/utils/setup.py_ was written with the **Register ALL users** use-case in mind, so it only subscribes you to the users added in that session. 

I created new ticket #12.

> Also when a user is registered when a new Plone user there is an attempt to register it towards all the Plone users, no matter what they are registered into the jabber server or not (even so I noticed the suggestion is sent but the user registered this way has no contacts in his list, this is a bug right?).

Yeah, sounds like a bug.

In line 67 in _collective.xmpp.core/subscribers/user_management.py_, the JIDs for all users in the Plone site are fetched.

So we need to get the JIDs of all users who are currently registered on XMPP, and only subscribe the user to those.

We can use this same approach for the other bug mentioned above.

Created new ticket #13

> For the 3rd way a user can be registered via the auto-register on login (the feature i implemented in this pull request) I made that the registered user is subscribed only to the users registered into the jabber server (not to try to subscribe it to all plone users no matter they are registered in jabber server or not). I think this the correct way of auto-subscribe that should be done for all 3 ways of registering users. 

I agree.

> I implemented this under https://github.com/alecghica/collective.xmpp.core/blob/bdb8cc5314c649c3e72437accd3d913f74f16a1c/collective/xmpp/core/browser/loader.py  see bellow line 51. About this I have a problem as I cant figure it out why even so _sendRosterItemAddSuggestion_ is receiving the right list of users and send the suggestion, the user didn't has the users in his contacts.

I would first make sure the roster suggestion is 100% correct. You can see the roster suggestion in the XMPP web admin (go to the user, and then _offline messages_). But first, you'll have to disable all the Javascript code that is listening for that suggestion (otherwise it will quickly disappear from the XMPP web admin as it's being processed).

If you are 100% sure the roster suggestion is correct, you'll have to look in converse.js to see how it is being handled there.

**Comment by alecghica** [comment]
@jcbrand I will fix #12 and #13, I assigned them to me.

**Comment by alecghica** [comment]
@jcbrand I am done on this pull request, I did the merge so you can merge it whenever you want to. For the auto-subscribe issues I'll do separate pull requests.

**Comment by alecghica** [comment]
Hi @jcbrand ,
Meanwhile I also fixed the auto-subscribe for all the possibilities to register an user. I also implemented that new users are now auto-subscribed only to existing XMPP users.

I also did some code cosmetics mostly to imports, I hope you are fine with them.

Waiting for your merge and for an eventual release (not really necessary). I was thinking maybe we should go for a more positive version of the package for both collective.xmpp.core and collective.xmpp.chat instead of 0.1a9 maybe to a stable 1.0 version?

**Comment by jcbrand** [comment]
Hi @alecghica 

Great job, thanks. I just did the merge.

Syslab is now already using *.core and *.chat in production (but with modified JS), so I agree we should definitely move out of alpha.

**Comment by alecghica** [comment]
Happy new year @jcbrand! I'll also add on production *.core and *.chat later on this month so at least two production usecases to prove the maturity and leave the alpha :)

**Comment by jcbrand** [comment]
Thanks @alecghica, for you too! I'm going to make releases this week.

**Comment by alecghica** [comment]
@jcbrand great, thx a lot!

**Pull request merged**
